name: etl
version: 0.0.1

require-dbt-version: ">=0.18.0"
config-version: 2

# Configure database connection profile for dbt to use
profile: 'etl'

# Set paths for dbt objects
analysis-paths: ["analysis"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

log-path: "logs"
#modules-path: "dbt_modules"
target-path: "target"
clean-targets:
    - "dbt_modules"
    - "target"

# Set query behavior: prepend comments and quoting
query-comment: "{{ query_comment(node) }}"
quoting:
  database: false
  schema: false
  identifier: false


# DBT MODELS
models:
    etl:
        +enabled: true
        +materialized: view
        +persist_docs:
            relation: true
            columns: true
        
        staging:
            +enabled: true
            +schema: intermediate
        
        marts:
            +enabled: true
            +materialized: table
            core:
                +schema: core
            marketing:
                +schema: marketing

        dbt_artifadts:
            schema:'ARTIFACTS'

# Project variables
vars:
    etl:
        dbt_project_created_date: '2020-09-21'  # <-- Set as date when dbt project first created
        analysis_start_date: '2016-01-01'  # <-- Earliest time when organization started tracking data
        analysis_end_date: dbt_utils.current_timestamp()
        source_database: lake  # <-- Set as name of the raw source database where data is ingested


# Data seeds
seeds:
    +quote_columns: false
    +schema: intermediate
    
    etl:
      +enabled: true

# Tests
data_tests:
    +severity:warn
    +store_failures:true
    +schema:'ARTIFACTS'

on-run-end:
    -"{{dbt_artifacts.upload_results(results)}}"