
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'etl'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'etl'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
analysis-paths: ["analysis"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

log-path: "logs"

# directories to be removed by `dbt clean`
target-path: "target"
clean-targets:
    - "dbt_modules"
    - "target"
    - "dbt_packages"

# Set query behavior: prepend comments and quoting
query-comment: "{{ query_comment(node) }}"
quoting:
  database: false
  schema: false
  identifier: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
    etl:
        +enabled: true
        +materialized: table
        +persist_docs:
            relation: true
            columns: true
        
        staging:
            +enabled: true
            +materialized: table

        marts:
            +enabled: true
            +materialized: table
            core:
                +schema: core
            marketing:
                +schema: marketing

    dbt_artifacts:
        schema:'ARTIFACTS'

# Project variables
vars:
    etl:
        dbt_project_created_date: '2025-01-01'  # <-- Set as date when dbt project first created
        analysis_start_date: '1970-01-01'  # <-- Earliest time when organization started tracking data
        analysis_end_date: dbt_utils.current_timestamp()
        source_database: staging  # <-- Set as name of the raw source database where data is ingested

# Data seeds
seeds:
    +quote_columns: false
    +schema: intermediate
    
    etl:
      +enabled: true

# Tests
data_tests:
    +severity: warn
    +store_failures: true
    +schema: 'ARTIFACTS'

on-run-end:
    - "{{dbt_artifacts.upload_results(results)}}"